### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm

### ISSUE THREAD

**Issue by wlupc** [alvaro-budria/NeuSacc#2]
Thanks your reply. when I run this code, there is a other error. The error is followings :

****************************************************************************************************************************************
 File "/home/wl/anaconda3/envs/NeuSacc/lib/python3.11/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
****************************************************************************************************************************************

My local gpu machine :
    my gpu is nvidia rtx 3080

My nvcc version message is the followings : 
    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2022 NVIDIA Corporation
    Built on Thu_Feb_10_18:23:41_PST_2022
    Cuda compilation tools, release 11.6, V11.6.112
    Build cuda_11.6.r11.6/compiler.30978841_0

Looking forward to your reply. Thanks.

**Comment by alvaro-budria** [comment]
This error message seems to hide an underlying OOM error. I tried reducing the resolution of the occupancy grid from 198 to 128 and observed a reduction in GPU memory consumption from over 20 Gb to less than 8 Gb.

I added the resolution as a parameter and set 128 as the default. Please try again with the code from `main` and reopen this issue if the problem persists.

**Comment by wlupc** [comment]
> This error message seems to hide an underlying OOM error. I tried reducing the resolution of the occupancy grid from 198 to 128 and observed a reduction in GPU memory consumption from over 20 Gb to less than 8 Gb.
> 
> I added the resolution as a parameter and set 128 as the default. Please try again with the code from `main` and reopen this issue if the problem persists.

Thanks your reply. I try to run this new code, but the issue still exist.  The error is following:
###############################################################################################
File "/home/wl/anaconda3/envs/NeuSacc/lib/python3.11/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
###############################################################################################

I don't know how to solve the problem.  Looking forward to your reply. :)

**Comment by alvaro-budria** [comment]
Could you please copy the entire error traceback here? Please, paste the traceback both from
`python exp_runner.py --mode train --conf ./confs/wmask_DTUscan.conf`

and from

`CUDA_LAUNCH_BLOCKING=1 python exp_runner.py --mode train --conf ./confs/wmask_DTUscan.conf`

Also, what version of PyTorch are you using?

Besides this, try to set some parameters in `confs/` to low values, such as `grid_prune = false`, `train_num_rays = 8`, `max_train_num_rays = 8`, `num_samples_per_ray = 8` and check if it still crashes.

I suspect this might be related to the computation of second derivatives w.r.t. to the inputs...

**Comment by wlupc** [comment]
> Could you please copy the entire error traceback here? Please, paste the traceback both from `python exp_runner.py --mode train --conf ./confs/wmask_DTUscan.conf`
> 
> and from
> 
> `CUDA_LAUNCH_BLOCKING=1 python exp_runner.py --mode train --conf ./confs/wmask_DTUscan.conf`
> 
> Also, what version of PyTorch are you using?
> 
> Besides this, try to set some parameters in `confs/` to low values, such as `grid_prune = false`, `train_num_rays = 8`, `max_train_num_rays = 8`, `num_samples_per_ray = 8` and check if it still crashes.
> 
> I suspect this might be related to the computation of second derivatives w.r.t. to the inputs...

Thanks your reply.  The entire error traceback is following : 
######################################################################################
(NeuSacc) wl@fa:~/work/NeuSacc$ python exp_runner.py --mode train --conf ./confs/wmask_DTUscan.conf
Hello Wooden
Device: NVIDIA GeForce RTX 3080
total GPU MEM   : 10737418240
free  GPU MEM   : 9556262912
used  GPU MEM   : 1181155328
Load data: Begin
Load data: End
Initializing VanillaFrequency mask:  tensor([1., 1., 1., 1., 1., 1.])
* SDFNetwork * - #Params = 14835125; #Trainable Params = 14835125
* RenderingNetwork * - #Params = 11264; #Trainable Params = 11264
[cmd.py:931 -              execute() ] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/wl/work/NeuSacc, universal_newlines=False, shell=None, istream=None)
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 3
wandb: You chose 'Don't visualize my results'
[cmd.py:931 -              execute() ] Popen(['git', 'cat-file', '--batch-check'], cwd=/home/wl/work/NeuSacc, universal_newlines=False, shell=None, istream=<valid stream>)
wandb: Tracking run with wandb version 0.13.7
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
  0%|                                                | 0/100000 [00:00<?, ?it/s]
wandb: Waiting for W&B process to finish... (failed 1).
wandb: You can sync this run to the cloud by running:
wandb: wandb sync ./exp/dtu_scan105/wmask_sphere/wandb/offline-run-20221228_100202-w2s77tb6
wandb: Find logs at: ./exp/dtu_scan105/wmask_sphere/wandb/offline-run-20221228_100202-w2s77tb6/logs
Traceback (most recent call last):
  File "/home/wl/work/NeuSacc/exp_runner.py", line 510, in <module>
    runner.train()
  File "/home/wl/work/NeuSacc/exp_runner.py", line 153, in train
    self.neus_model.update_step(-1, iter_i)
  File "/home/wl/work/NeuSacc/models/neus.py", line 69, in update_step
    self.occupancy_grid.every_n_step(
  File "/home/wl/anaconda3/envs/NeuSacc/lib/python3.11/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wl/anaconda3/envs/NeuSacc/lib/python3.11/site-packages/nerfacc/grid.py", line 271, in every_n_step
    self._update(
  File "/home/wl/anaconda3/envs/NeuSacc/lib/python3.11/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wl/anaconda3/envs/NeuSacc/lib/python3.11/site-packages/nerfacc/grid.py", line 229, in _update
    occ = occ_eval_fn(x).squeeze(-1)
          ^^^^^^^^^^^^^^
  File "/home/wl/work/NeuSacc/models/neus.py", line 56, in occ_eval_fn
    sdf = self.geometry.sdf(x, training=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wl/work/NeuSacc/models/fields.py", line 88, in sdf
    return self.forward(x, training=training)[:, :1]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wl/work/NeuSacc/models/fields.py", line 83, in forward
    x = self.mlp_sdf(inputs)
        ^^^^^^^^^^^^^^^^^^^^
  File "/home/wl/anaconda3/envs/NeuSacc/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wl/anaconda3/envs/NeuSacc/lib/python3.11/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/home/wl/anaconda3/envs/NeuSacc/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wl/work/NeuSacc/models/model_components.py", line 48, in forward
    x = self.layers(x.float())
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wl/anaconda3/envs/NeuSacc/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wl/anaconda3/envs/NeuSacc/lib/python3.11/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/home/wl/anaconda3/envs/NeuSacc/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wl/anaconda3/envs/NeuSacc/lib/python3.11/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
################################################################################################
Another, My version of torch is 1.13.1
I will try to use the parameters which you suggest to run the code. 

Thanks for your feedback again! :)

**Comment by alvaro-budria** [comment]
In your answer there seems to be only one trace stack. Did you also copy the one generated by `CUDA_LAUNCH_BLOCKING=1 python exp_runner.py --mode train --conf ./confs/wmask_DTUscan.conf` ? It can help me see if I have faced the same error before.

Also, could you try using version `1.12.1`  of PyTorch? Sorry for the inconvenience.

**Comment by wlupc** [comment]
> In your answer there seems to be only one trace stack. Did you also copy the one generated by `CUDA_LAUNCH_BLOCKING=1 python exp_runner.py --mode train --conf ./confs/wmask_DTUscan.conf` ? It can help me see if I have faced the same error before.
> 
> Also, could you try using version `1.12.1` of PyTorch? Sorry for the inconvenience.

Thanks your reply. I use the command " CUDA_LAUNCH_BLOCKING=1 python exp_runner.py --mode train --conf ./confs/wmask_DTUscan.conf " to generate, but the error is persist. The following is the result: 
##########################################################################################
(NeuSacc) wl@fa:~/work/NeuSacc$ CUDA_LAUNCH_BLOCKING=1 python exp_runner.py --mode train --conf ./confs/wmask_DTUscan.conf
Hello Wooden
Device: NVIDIA GeForce RTX 3080
total GPU MEM   : 10737418240
free  GPU MEM   : 9762045952
used  GPU MEM   : 975372288
Load data: Begin
Load data: End
Initializing VanillaFrequency mask:  tensor([1., 1., 1., 1., 1., 1.])
* SDFNetwork * - #Params = 14835125; #Trainable Params = 14835125
* RenderingNetwork * - #Params = 11264; #Trainable Params = 11264
[cmd.py:931 -              execute() ] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/wl/work/NeuSacc, universal_newlines=False, shell=None, istream=None)
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 3
wandb: You chose 'Don't visualize my results'
[cmd.py:931 -              execute() ] Popen(['git', 'cat-file', '--batch-check'], cwd=/home/wl/work/NeuSacc, universal_newlines=False, shell=None, istream=<valid stream>)
wandb: Tracking run with wandb version 0.13.7
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
  0%|                                                                                                           | 0/100000 [00:00<?, ?it/s]
wandb: Waiting for W&B process to finish... (failed 1).
wandb: You can sync this run to the cloud by running:
wandb: wandb sync ./exp/dtu_scan105/wmask_sphere/wandb/offline-run-20221229_085335-2ar71uq6
wandb: Find logs at: ./exp/dtu_scan105/wmask_sphere/wandb/offline-run-20221229_085335-2ar71uq6/logs
Traceback (most recent call last):
  File "/home/wl/work/NeuSacc/exp_runner.py", line 510, in <module>
    runner.train()
  File "/home/wl/work/NeuSacc/exp_runner.py", line 153, in train
    self.neus_model.update_step(-1, iter_i)
  File "/home/wl/work/NeuSacc/models/neus.py", line 69, in update_step
    self.occupancy_grid.every_n_step(
  File "/home/wl/anaconda3/envs/NeuSacc/lib/python3.11/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wl/anaconda3/envs/NeuSacc/lib/python3.11/site-packages/nerfacc/grid.py", line 271, in every_n_step
    self._update(
  File "/home/wl/anaconda3/envs/NeuSacc/lib/python3.11/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wl/anaconda3/envs/NeuSacc/lib/python3.11/site-packages/nerfacc/grid.py", line 229, in _update
    occ = occ_eval_fn(x).squeeze(-1)
          ^^^^^^^^^^^^^^
  File "/home/wl/work/NeuSacc/models/neus.py", line 56, in occ_eval_fn
    sdf = self.geometry.sdf(x, training=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wl/work/NeuSacc/models/fields.py", line 88, in sdf
    return self.forward(x, training=training)[:, :1]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wl/work/NeuSacc/models/fields.py", line 83, in forward
    x = self.mlp_sdf(inputs)
        ^^^^^^^^^^^^^^^^^^^^
  File "/home/wl/anaconda3/envs/NeuSacc/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wl/anaconda3/envs/NeuSacc/lib/python3.11/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/home/wl/anaconda3/envs/NeuSacc/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wl/work/NeuSacc/models/model_components.py", line 48, in forward
    x = self.layers(x.float())
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wl/anaconda3/envs/NeuSacc/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wl/anaconda3/envs/NeuSacc/lib/python3.11/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/home/wl/anaconda3/envs/NeuSacc/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wl/anaconda3/envs/NeuSacc/lib/python3.11/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
################################################################################################
I try to change the version of pytorch to 1.12.1 ,  then to run this code. Thanks your help. :)

**Comment by alvaro-budria** [comment]
Did you try to set some of the parameters to low values to see if reducing the memory consumption helps? I didn't mention it in my previous comment, but please also try setting `resolution_occ_grid = 16`. I really need to discard the possibility of being a VRAM issue before looking at other causes.
